import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "La Pinamarense",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` fuentePrincipal antialiased lg:h-[100dvh]   `}
      >
        {children}
      </body>
    </html>
  );
}
